name: Publish Development

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Tag For Build"
        required: true
        default: ""
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract MetaData (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            excalith/start-page
            ghcr.io/excalith/excalith-start-page

      - name: Build and Push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            excalith/start-page:${{ inputs.name }}
            ghcr.io/excalith/excalith-start-page:${{ inputs.name }}
          platforms: linux/amd64,linux/arm64
